// import 'package:dpay/l10n/locals.dart';
// import 'package:flutter/widgets.dart';
// import 'package:flutter_localization/flutter_localization.dart';

final List<String> listOfBanks = [
  'State Bank of India (SBI)',
  'ICICI Bank',
  'HDFC Bank',
  'Axis Bank',
  'Kotak Mahindra Bank',
  'IDFC First Bank',
  'Bank of Baroda (BOB)',
  'Punjab National Bank (PNB)',
  'Union Bank of India',
  'IndusInd Bank',
  'Canara Bank',
  'Yes Bank',
  'Federal Bank',
  'Punjab & Sind Bank',
  'South Indian Bank',
  'Karur Vysya Bank',
  'Equitas Small Finance Bank',
  'AU Small Finance Bank',
  'Fino Payments Bank',
  'Paytm Payments Bank',
];

final List<String> listOfElectricityProviderCompanys = [
  'NTPC Limited',
  'Power Grid Corporation of India Limited (POWERGRID)',
  'Tata Power',
  'Adani Power',
  'Reliance Infrastructure',
  'JSW Energy',
  'Torrent Power',
  'NLC India Limited',
  'NHPC Limited',
  'CESC Limited',
  'BSES Rajdhani Power Limited (BRPL)',
  'BSES Yamuna Power Limited (BYPL)',
  'Tata Power Delhi Distribution Limited (Tata Power-DDL)',
  'Uttar Gujarat Vij Company Limited (UGVCL)',
];

List<String> listOfBrodbandServiceProviderCompanys = [
  'Comcast Xfinity',
  'AT&T Internet',
  'Verizon Fios',
  'Charter Spectrum',
  'Cox Communications',
  'CenturyLink',
  'Frontier Communications',
  'Optimum by Altice',
  'RCN',
  'Mediacom',
];

List<String> listOfPrpedGasServiceProviderCompanys = [
  'Indraprastha Gas Limited (IGL)',
  'Mahanagar Gas Limited (MGL)',
  'Adani Gas Limited',
  'Gujarat Gas Limited (GGL)',
  'GAIL Gas Limited',
  'Tripura Natural Gas Company Limited (TNGCL)',
  'Bhagyanagar Gas Limited (BGL)',
  'Green Gas Limited',
];

List<String> listOfWaterServiceProviderCompanys = [
  'Bengaluru Water Supply and Sewerage Board (BWSSB)',
  'Delhi Jal Board (DJB)',
  'Chennai Metropolitan Water Supply and Sewerage Board (CMWSSB)',
  'Mumbai Metropolitan Region Development Authority (MMRDA)',
  'Hyderabad Metropolitan Water Supply and Sewerage Board (HMWSSB)',
  'Kolkata Municipal Corporation (KMC)',
  'Pune Municipal Corporation (PMC)',
  'Ahmedabad Municipal Corporation (AMC)',
  'Lucknow Jal Sansthan',
  'Jaipur Nagar Nigam (JNN)',
];

// new data

final List<String> name = [
  'John',
  'Mary',
  'David',
  'Sarah',
  'Michael',
  'Jessica',
  'James',
  'Emily',
  'Robert',
  'Jennifer',
  'William',
  'Emma',
  'Joseph',
  'Olivia',
  'Daniel',
  'Ava',
  'Matthew',
  'Sophia',
  'Andrew',
  'Isabella',
  'Anthony',
  'Charlotte',
  'Christopher',
  'Amelia',
  'Elizabeth',
  'Benjamin',
  'Grace',
  'Alexander',
  'Ethan',
  'Mia',
  'Daniel',
  'Liam',
  'Chloe',
  'Gabriel',
  'Natalie',
  'Joshua',
  'Zoe',
  'Samuel',
  'Hannah',
  'Lucas',
  'Madison',
  'Jacob',
  'Lily',
  'Henry',
  'Victoria',
  'Nathan',
  'Anna',
  'Ryan',
  'Ella',
  'Charles',
  // 'Samantha',
];

final List<String> bankName = [
  'State Bank of India',
  'ICICI Bank',
  'HDFC Bank',
  'Axis Bank',
  'Kotak Mahindra Bank',
  'IDFC First Bank',
  'Bank of Baroda',
  'Punjab National Bank',
  'Union Bank of India',
  'IndusInd Bank',
  'Canara Bank',
  'Yes Bank',
  'Federal Bank',
  'Punjab & Sind Bank',
  'South Indian Bank',
  'Karur Vysya Bank',
  'Equitas Small Finance Bank',
  'AU Small Finance Bank',
  'Fino Payments Bank',
  'Paytm Payments Bank',
  'Indian Bank',
  'Bank of India',
  'Indian Overseas Bank',
  'UCO Bank',
  'Central Bank of India',
  'IDBI Bank',
  'Bank of Maharashtra',
  'Allahabad Bank',
  'Andhra Bank',
  'Syndicate Bank',
  'Oriental Bank of Commerce',
  'UCO Bank',
  'Vijaya Bank',
  'Dena Bank',
  'Corporation Bank',
  'United Bank of India',
  'Indian Bank',
  'Bank of India',
  'Indian Overseas Bank',
  'UCO Bank',
  'Central Bank of India',
  'IDBI Bank',
  'Bank of Maharashtra',
  'Allahabad Bank',
  'Andhra Bank',
  'Syndicate Bank',
  'Oriental Bank of Commerce',
  'UCO Bank',
  'Vijaya Bank',
  'Dena Bank',
  // 'Corporation Bank',
];
